### PR TITLE
ci: make some scorecard security suggestions

### PR DESCRIPTION
**Pull request by asraa**
* Adds top-level read only perms to some github workflows
* Pins some dependencies

### CODE REVIEW

**Comment by AlexanderViand-Intel** [comment]
Let's use this opportunity (having to specify hashes for the dependencies) to also fix the "broken" `requirements.txt` (I think we currently require a yanked version?):

```
$ pip install -r  requirements.txt 
Collecting tomli==2.0.1 (from -r requirements.txt (line 2))
  Downloading tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting sympy==1.12 (from -r requirements.txt (line 3))
  Downloading sympy-1.12-py3-none-any.whl.metadata (12 kB)
Collecting mpmath==1.3.0 (from -r requirements.txt (line 4))
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting jaxite==0.0.2 (from -r requirements.txt (line 7))
  Downloading jaxite-0.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting jax~=0.4.25 (from -r requirements.txt (line 8))
  Downloading jax-0.4.34-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib~=0.4.25 (from -r requirements.txt (line 9))
  Downloading jaxlib-0.4.34-cp312-cp312-manylinux2014_x86_64.whl.metadata (983 bytes)
ERROR: Ignored the following yanked versions: 1.11.0, 1.14.0rc1
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.9.2, 1.9.3, 1.11.0rc1, 1.11.0rc2, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc1, 1.13.0, 1.13.1, 1.14.0rc2, 1.14.0, 1.14.1)
ERROR: No matching distribution found for scipy==1.10.1
```

**Comment by asraa** [comment]
Oh yeah, I'm working on it now - haha let me mark this as draft

**Review by j2kun — APPROVED** [review]

**Comment by asraa** [comment]
Fixed up the python dependencies that were yanked!

**Comment by AlexanderViand-Intel** [comment]
Awesome, thanks for tackling these!

**Review by j2kun — APPROVED** [review]

**Comment by j2kun** [comment]
TIL about all these features. Very cool

**Pull request merged**
