### PR TITLE
fix gcc build of rapidjson

### PR DESCRIPTION
**Pull request by inbelic**
- update rapidjson repo to include commit that removes assignment of
      read-only member error

see https://github.com/Tencent/rapidjson/issues/2277#issuecomment-2238470733

### CODE REVIEW

**Comment by j2kun** [comment]
!!! 

> The fix was merged in 2016 😱

**Review by j2kun — APPROVED** [review]

**Comment by AlexanderViand-Intel** [comment]
> !!!
> 
> > The fix was merged in 2016 😱

It looks like rapidjson is basically abandonware :( There are dozens of issues on their repo asking for new releases, especially since one lone maintainer does seem to occasionally merge a few fixes. 

@j2kun? Do we we need the speed of rapidjson, or could we swap to something more well-maintend, like nlohmann/json?

**Comment by j2kun** [comment]
The obstacle is mainly what libraries are already inside Googles monorepo. I can check, and if not it's a bit of extra work to integrate a new library (and I'd be the long term maintainer of that new library internally)

**Comment by asraa** [comment]
> The obstacle is mainly what libraries are already inside Googles monorepo. I can check, and if not it's a bit of extra work to integrate a new library (and I'd be the long term maintainer of that new library internally)

Actually rapidjson is so abandonware that we get internal presubmit warning asking us to not use it and to use nlohmann/json. I used to be on the team that added that presubmit warning because our json fuzzers for rapidjson had so many open bugs. I can migrate it over! I'll open a bug.

**Review by asraa — APPROVED** [review]

**Pull request merged**
