### PR TITLE
comb-to-cggi: add secret memref allocation conversion

### PR DESCRIPTION
**Pull request by asraa**
Fixes https://github.com/google/heir/issues/361

This commit: https://github.com/google/heir/pull/363/commits/987335eb8d1f59434a94fb216ab0200f6ca0757c
Fixes https://github.com/google/heir/issues/365

### CODE REVIEW

**Comment by asraa** [comment]
This is finally ready for review! It took my a very long time to understand how to deal with the memref accesses and resulting layouts. I'm happy to walk through an example.

**Review by j2kun — CHANGES_REQUESTED** [review]
Amazing. Well done! Looks like there is a slight filecheck error there, but it seems like it is trivial to fix.

**Comment by asraa** [comment]
Test fixed, thanks!

**Comment by j2kun** [comment]
Looks like it still needs a fix.

**Review by j2kun — APPROVED** [review]

**Pull request merged**
