### PR TITLE
Add `SameOperandsAndResultRings` trait to BGV ops

### PR DESCRIPTION
**Pull request by mr0re1**
* Add `SameOperandsAndResultRings` trait to BGV ops;
* Simplify some assembly formats;
* Add `SameTypeOperands` trait to `BGV_MulOp`.

**Follow up:** come up with format that takes advantage of `SameOperandsAndResultRings`.

### CODE REVIEW

**Comment by j2kun** [comment]
This looks awesome! LGTM.

Is the followup specifically about assembly formats? Or are you trying to do something more with this trait?

**Review by j2kun — APPROVED** [review]

**Comment by j2kun** [comment]
CC @asraa for the permissions error about the pull_ready label. Adding it manually.

**Comment by mr0re1** [comment]
> Is the followup specifically about assembly formats? Or are you trying to do something more with this trait?

I was thinking about implementing `custom< SameOperandsAndResultRings>` printer/parser for assembly format. But number of options is rather large and requires more consideration.

**Review by asraa — APPROVED** [review]
This is really cool!

**Pull request merged**
