### PR TITLE
CKKS: place mgmt ops and add RNS lowering

### PR DESCRIPTION
**Pull request by ZenithalHourlyRate**
This is a mirror of #1126.

However, the complicacy is that in the CKKS pipeline we support _tensor of ciphertext_, which renders the following difficulties

* tensor::ExtractOp has two semantic (mentioned in #1174)
* ckks::RescaleOp takes `tensor of ciphertext` as input, which only accepts RLWECiphertext but not RLWECiphertextLike.
* In `tests/Dialect/Secret/Conversions/secret_to_ckks/matmul_loop.mlir`, `affine` is not unrolled so `LevelAnalysis` can not work. It should not work as we do not have loop invariant kept here. For example, for the loop to carry out correctly in FHE, the invariant is `the level is the same`, which heavily depends on the body.

  More case analysis here. The body is a mul_plain + add, which in different mgmt op placement strategy there will be different level analysis result. For example, if we mod reduce immediately after mul_plain, we get the level reduced by one hence the invariant is not kept. For the current strategy we fortunately kept this invariant.

My current workarounds over these are

* Copy the secret-to-ckks code on deciding whether to pack tensor into ciphertext, then annotate these tensor::ExtractOp to distinguish semantic so that various analysis could work.
* Fully unroll the tensor, namely for each element we generate a ckks.rescale.
* I prefer to disable `matmul_loop.mlir` for now, asking the user to full-loop-unroll. In the future, I should make the analysis establishing invariant and error out when user wrote some invariant-broken code, so that we can have correct level analysis for loops.

### CODE REVIEW

**Review by j2kun — APPROVED** [review]
LGTM! Generally ok with the workarounds for now.

**Comment by j2kun** [comment]
You will need to rebase to fix the build error I unfortunately pushed to main earlier today.

**Comment by ZenithalHourlyRate** [comment]
Rebased and squashed.

**Comment by ZenithalHourlyRate** [comment]
Fixed the building. Seems that mlir::arith and mlir::heir::arith (added by arith to mod arith) has some name conflict.

**Comment by AlexanderViand-Intel** [comment]
This just got copybara-merged, but things look a bit funky?

**Comment by asraa** [comment]
I have a feeling [9315298](https://github.com/google/heir/commit/931529889653bd1201cdfef5383f30a942bf18ac) was merged and that's why github didn't recognize this as merged. (I think jeremy cloned this and fixed the internal build issues at that commit?)

**Pull request closed without merging**
