### PR TITLE
switch `-convert-polynomial-mul-to-ntt` to use `arith_ext.mul`

### LINKED ISSUE #724: Accelerator-Friendly Lowering of polynomial.mul to NTT
_copied from my discord post earlier today_

As part of the heir->DPRIVE-style accelerator flow, I've been thinking about the NTT rewrite of `polynomial.mul`  (i.e., replacing a polynomial  `mul` with `ntt` + elementwise mul + `intt`).
Currently, the "elementwise mul" in that is represented like this:
```llvm
%2 = arith.extui %0 : tensor<4xi5, #ring> to tensor<4xi10, #ring>
%3 = arith.extui %1 : tensor<4xi5, #ring> to tensor<4xi10, #ring>
%4 = arith.muli %2, %3 : tensor<4xi10, #ring>
%5 = arith.remui %4, %cst : tensor<4xi10, #ring>
%6 = arith.trunci %5 : tensor<4xi10, #ring>
```
which makes perfect sense, but is somewhat annoying to deal with for HW where "multiplication modulo `cmod`" is a native operation.

Right now, I'm sidestepping the issue by not using `--convert-polynomial-mul-to-ntt`, but that's clearly not ideal: one of the basic, but very important, optimizations HEIR should do at the `polynomial` level is to get rid of redundant `ntt`/`intt`  operations and of course those need to happen after `--convert-polynomial-mul-to-ntt`.

My first idea to solve this would be to introduce a `poly_ext` (or `tensor_ext` ?) operation that takes two tensors and a ring attribute and represents the elementwise modular multiplication. Then the current `--convert-polynomial-mul-to-ntt` would be split into two, the first part only going to that `elementwise_mul` (or similar) operation, and a second pass that lowers that to the `arith` implementation above.

Thoughts? Am I missing a better solution here? Pinging @inbelic :wink:

### PR DESCRIPTION
**Pull request by AlexanderViand-Intel**
Fixes #724

Draft, because it's currently still based off of #731 (arith_ext improvements)

### CODE REVIEW

**Review by j2kun — APPROVED** [review]
LGTM for the last commit in the chain.

**Comment by j2kun** [comment]
Ready to rebase

**Comment by AlexanderViand-Intel** [comment]
> Ready to rebase

Thanks, rebased :)

**Review by j2kun — APPROVED** [review]

**Comment by j2kun** [comment]
Still marked as a draft, but let me know if it's ready to pull

**Pull request merged**
