### PR TITLE
[mod_arith] move arith_ext dialect to mod_arith

### PR DESCRIPTION
**Pull request by inbelic**
- originally arith_ext was added to house a couple extra
      (modulus-based) operations to help represent the optimizations in
      the HEaan.mlir paper
    - however, there has been a need for other modular arithmetic
      operations and they have been added to the arith_ext dialect
    - as such, it was decided to move this to a specific mod_arith
      dialect to be more concrete and better describe the operations

### CODE REVIEW

**Comment by inbelic** [comment]
I haven't built this locally with CMake. Is that covered in the workflow here?

**Comment by j2kun** [comment]
If you're not using pre-commit, try applying the patch manually: https://github.com/google/heir/actions/runs/10376987295/job/28774854361?pr=907

**Review by j2kun — APPROVED** [review]

**Comment by inbelic** [comment]
Whoops, forgot to re-install pre-commit on my new install.
Force-pushed to rebase onto main and resolve conflicts

**Review by asraa — APPROVED** [review]
LGTM!

**Pull request merged**
