### PR TITLE
default to clang/lld + add gcc config

### PR DESCRIPTION
**Pull request by AlexanderViand-Intel**
As discussed on discord :)

### CODE REVIEW

**Review by j2kun — APPROVED** [review]

**Review by asraa — APPROVED** [review]
Hey! Sorry for the delay, I hit some bugs when I was testing this (tbh, I build with gcc and it works fine but mostly i'm doing internal dev that works seamlessly). I also needed to install `libstdc++-14-dev`, which was the version used by clang (checked `clang -v`) to avoid missing standard C++ headers.

It also turns out that clang version 18 didn't work for me (layering checks in llvm didn't work). Might be worth specifying that clang version XYZ has been tested for this default build - for me, clang 16 worked find.

**Comment by AlexanderViand-Intel** [comment]
> It also turns out that clang version 18 didn't work for me (layering checks in llvm didn't work). Might be worth specifying that clang version XYZ has been tested for this default build - for me, clang 16 worked find.

Interesting, my clang version is 18.1.3 and all heir targets build fine (Ubuntu 22.04, pretty much a fresh machine with just HEIR and its requirements on it). Any idea what might be different here?

**Comment by j2kun** [comment]
Layering checks are a Google internal thing, not enforced externally, right?

**Comment by AlexanderViand-Intel** [comment]
> //tests/convert_secret_insert_to_static_insert:secret_inserts.mlir.test  FAILED in 0.7s

WTF? This passes locally, and I don't see how clang vs gcc could make a difference here? (Actually, I'm not even sure if the CI uses the default config or manually specifies gcc?) Maybe another flakey test?

**Comment by asraa** [comment]
> Layering checks are a Google internal thing, not enforced externally, right?

I'm building externally with a clang 18 version installed from llvm's github release... so maybe there's some flag but that's weird

>  Any idea what might be different here?

OK! I'll keep it as is and merge - if someone finds an issue besides me I'll chime in

> WTF? This passes locally, and I don't see how clang vs gcc could make a difference here? (Actually, I'm not even sure if the CI uses the default config or manually specifies gcc?) Maybe another flakey test?

Yep - flakey test https://github.com/google/heir/issues/987. I understand the issue and spent a little time on Friday fixing it, but I didn't get done yet.

**Comment by asraa** [comment]
> layering checks in llvm didn't work

I found out that the "module does not depend on" error I was getting from the LLVM repo was actually most likely because of my bazel version (and I used features=-module_maps to disable it)

**Comment by asraa** [comment]
OK the exact error I get, but note that I could build the `heir-opt` target fine, but when i tried to build a test I got this failure:

```
$ bazel build -c dbg  @heir//tests/convert_secret_insert_to_static_insert:secret_inserts.mlir.test
INFO: Analyzed target //tests/convert_secret_insert_to_static_insert:secret_inserts.mlir.test (3 packages loaded, 13685 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/asraa/.cache/bazel/_bazel_asraa/dd6a35b586d0a2d65a5a8939e7a649cf/external/llvm-project/mlir/BUILD.bazel:13158:11: Compiling mlir/lib/Dialect/Math/Transforms/ExtendToSupportedTypes.cpp failed: (Exit 1): clang failed: error executing command (from target @llvm-project//mlir:MathTransforms) /usr/lib/llvm-16/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g ... (remaining 104 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/llvm-project/mlir/lib/Dialect/Math/Transforms/ExtendToSupportedTypes.cpp:16:10: error: module @llvm-project//mlir:MathTransforms does not depend on a module exporting 'mlir/Dialect/Arith/Utils/Utils.h'
#include "mlir/Dialect/Arith/Utils/Utils.h"
         ^
1 error generated.
Target //tests/convert_secret_insert_to_static_insert:secret_inserts.mlir.test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.448s, Critical Path: 10.74s
INFO: 65 processes: 65 internal.
FAILED: Build did NOT complete successfully
```

**Pull request merged**
