### PR TITLE
Rename poly -> polynomial

### PR DESCRIPTION
**Pull request by j2kun**
Fixes https://github.com/google/heir/issues/207

I did NOT rename poly_ext, but everything else involving 'poly' should be renamed

### CODE REVIEW

**Review by AlexanderViand-Intel — CHANGES_REQUESTED** [review]
LGTM, but will need to be rebased and fix the uses of `poly` introduced by recently merged PRs, i.e., renaming things like `registerPolyToStandardPasses` and `polyToLLVMPipelineBuilder`.

**Comment by j2kun** [comment]
Done!

**Comment by j2kun** [comment]
@asraa stamp for internal?

**Review by AlexanderViand-Intel — APPROVED** [review]

**Review by asraa — APPROVED** [review]
Done!

**Pull request merged**
