### PR TITLE
Improve doc generation script

### PR DESCRIPTION
**Pull request by j2kun**
This PR does two things:

- Convert the docs generation bash script into a python script.
- Change the passes docs page so that all passes are listed on a single page, with sections sorted by the flag name.

### CODE REVIEW

**Comment by j2kun** [comment]
image

**Review by AlexanderViand-Intel — CHANGES_REQUESTED** [review]
Quick mini-review, as I noticed this while trying to view the changes locally:
the docs `README` needs to be updated to reflect the new command.

EDIT: built locally and looks great!

**Comment by j2kun** [comment]
> Quick mini-review, as I noticed this while trying to view the changes locally: the docs `README` needs to be updated to reflect the new command.
> 
> EDIT: built locally and looks great!

Done!

**Review by AlexanderViand-Intel — APPROVED** [review]
:heart:

**Pull request merged**
