### PR TITLE
Enable deterministic run of transforms 

### PR DESCRIPTION
**Pull request by ai-mannamalai**
Enable deterministic run of transforms

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
woah! very cool. if this works you should be able to update the line in this test https://github.com/google/heir/blob/40f424e47bd5bc6924d9fbdfe465efe976af091d/tests/cggi/straight_line_vectorizer.mlir#L93-L97

to something where the `[[num:.*]]` is known, hopefully to back to 8 vectorized lut3's followed by their not (otherwise, it'll be a DAG of 7 lut3s, 1 not, 1 lut3)
```
 // CHECK: cggi.lut3 %[[arg1:.*]], %[[arg2:.*]], %[[arg3:.*]] {lookup_table = 8 : ui8} : tensor<8x!lwe.lwe_ciphertext
  // CHECK: cggi.not
```

**Comment by ai-mannamalai** [comment]
> heir/tests/cggi/straight_line_vectorizer.mlir

vectorize and canonicalize yields,

```
    %from_elements = tensor.from_elements %extracted_2, %extracted_3, %extracted, %extracted_1, %extracted_6, %extracted_2, %extracted : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %from_elements_7 = tensor.from_elements %extracted_3, %extracted_4, %extracted_2, %extracted_4, %extracted_0, %extracted_5, %extracted_0 : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %from_elements_8 = tensor.from_elements %extracted_4, %extracted_5, %extracted_0, %extracted_5, %extracted_5, %extracted, %extracted_1 : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %0 = cggi.lut_lincomb %from_elements, %from_elements_7, %from_elements_8 {coefficients = array<i32: 1, 2, 4>, lookup_table = 8 : ui8} : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %extracted_9 = tensor.extract %0[%c0] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %extracted_10 = tensor.extract %0[%c1] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %extracted_11 = tensor.extract %0[%c2] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %extracted_12 = tensor.extract %0[%c3] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %extracted_13 = tensor.extract %0[%c4] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %extracted_14 = tensor.extract %0[%c6] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    %1 = cggi.lut_lincomb %extracted_4, %extracted_5, %extracted_6 {coefficients = array<i32: 1, 2, 4>, lookup_table = 8 : ui8} : !lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>
    %2 = cggi.not %1 : !lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>
    %from_elements_15 = tensor.from_elements %extracted_14, %extracted_9, %extracted_10, %1, %extracted_11, %extracted_12, %extracted_13, %2 : tensor<8x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
    return %from_elements_15 : tensor<8x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
  }
}

```

**Comment by ai-mannamalai** [comment]
> > heir/tests/cggi/straight_line_vectorizer.mlir
> 
> vectorize and canonicalize yields,
> 
> ```
>     %from_elements = tensor.from_elements %extracted_2, %extracted_3, %extracted, %extracted_1, %extracted_6, %extracted_2, %extracted : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %from_elements_7 = tensor.from_elements %extracted_3, %extracted_4, %extracted_2, %extracted_4, %extracted_0, %extracted_5, %extracted_0 : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %from_elements_8 = tensor.from_elements %extracted_4, %extracted_5, %extracted_0, %extracted_5, %extracted_5, %extracted, %extracted_1 : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %0 = cggi.lut_lincomb %from_elements, %from_elements_7, %from_elements_8 {coefficients = array<i32: 1, 2, 4>, lookup_table = 8 : ui8} : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %extracted_9 = tensor.extract %0[%c0] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %extracted_10 = tensor.extract %0[%c1] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %extracted_11 = tensor.extract %0[%c2] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %extracted_12 = tensor.extract %0[%c3] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %extracted_13 = tensor.extract %0[%c4] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %extracted_14 = tensor.extract %0[%c6] : tensor<7x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     %1 = cggi.lut_lincomb %extracted_4, %extracted_5, %extracted_6 {coefficients = array<i32: 1, 2, 4>, lookup_table = 8 : ui8} : !lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>
>     %2 = cggi.not %1 : !lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>
>     %from_elements_15 = tensor.from_elements %extracted_14, %extracted_9, %extracted_10, %1, %extracted_11, %extracted_12, %extracted_13, %2 : tensor<8x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>     return %from_elements_15 : tensor<8x!lwe.lwe_ciphertext<encoding = #lwe.unspecified_bit_field_encoding<cleartext_bitwidth = 3>>>
>   }
> }
> ```

I'm not fully grasping the idea of the straight line vectorizer yet; so my patch right now is to only fix the logical return flag and see if that fixes it but doesn't seem to be the case.

**Comment by ai-mannamalai** [comment]
> > vectorize and canonicalize yields,
> 
> OK gotcha - it looks like it's doing the 7 lut3s, then the 1 not, then the 1 lut3. So you can update the checks to
> 
> ```
>  // CHECK: cggi.lut_lincomb %[[arg1:.*]], %[[arg2:.*]], %[[arg3:.*]] {coefficients = array<i32: 1, 2, 4>, lookup_table = 8 : ui8} : tensor<7x!lwe.lwe_ciphertext
>  // CHECK: cggi.not
>  // CHECK: cggi.lut_lincomb
> ```
> 
> It might be the case that fixing that made it deterministic though! There were two possible paths and it does hit one of them.

this passed! thanks I merged my 2 commits and updated the patch

**Pull request merged**
